user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
checked: 1
size: 80
per_page: 10
pass_rs:
  rs_sent_at: 2
micropost:
  max_length: 140
user_info:
  size: 50
micropost_html:
  size: 50
time_zone: "Hanoi"
show_follow:
  size: 30
picture_size: 5
